server:
  port: 8080
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  profiles:
    active: test
  datasource:
    # https://www.baeldung.com/spring-boot-h2-database#h2-database-url-options
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;
    #    url: jdbc:h2:file:./target/h2.db;AUTO_SERVER=true
    #    url: jdbc:h2:tcp://localhost:9092/mem:testdb
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
#    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    # Apenas para teste
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  lifecycle:
    timeout-per-shutdown-phase: "5s"
management:
  endpoints:
    web:
      exposure:
        include: health,info,shutdown
  endpoint:
    shutdown:
      enabled: true
#logging:
#  level:
#    root: DEBUG