server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATA_SOURCE_USERNAME:root}
    password: ${SPRING_DATA_SOURCE_PASSWORD:root}
    url: ${SPRING_DATA_SOURCE_URL:jdbc:postgresql://localhost:5432/backend}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect